In [1]:
import jax
import jax.numpy as jnp

In [32]:
a = jnp.array(2.)

In [49]:
b = jnp.array([1., 2., 3., 4.])
x = jnp.array([4., 4., 4., 4.])

In [50]:
def f(a, b, x):
  return a * jnp.dot(b,x)

In [51]:
f(a,b,x)

DeviceArray(80., dtype=float32)

In [52]:
grad_f = jax.grad(fun=f, argnums=2)
grad_f(a,b,x)

DeviceArray([2., 4., 6., 8.], dtype=float32)

In [53]:
x_batch = jnp.array([[1.,1.,1.,1.],[2.,2.,2.,2.],[3.,3.,3.,3.],[4.,4.,4.,4.]])

print(jax.vmap(grad_f,in_axes=[None,None,0])(a,b,x_batch))
print(jax.vmap(f,in_axes=[None,None,0])(a,b,x_batch))

[[2. 4. 6. 8.]
 [2. 4. 6. 8.]
 [2. 4. 6. 8.]
 [2. 4. 6. 8.]]
[20. 40. 60. 80.]


In [55]:
f_jitted = jax.jit(f)
f_jitted(a,b,x)

DeviceArray(80., dtype=float32)

In [57]:
jax.make_jaxpr(f_jitted)(a,b,x)

{ lambda  ; a b c.
  let d = xla_call[ backend=None
                    call_jaxpr={ lambda  ; a b c.
                                 let d = dot_general[ dimension_numbers=(((0,), (0,)), ((), ()))
                                                      precision=None ] b c
                                     e = mul a d
                                 in (e,) }
                    device=None
                    donated_invars=(False, False, False)
                    name=f ] a b c
  in (d,) }

In [58]:
jax.local_devices()

[GpuDevice(id=0)]